name       : ajour
version    : 1.3.0
release    : 7
source     :
    - https://github.com/ajour/ajour/archive/refs/tags/1.3.0.tar.gz : 72695ce09603001fb91c9cd5a73c13b2878859608d9a26d239fe1a7b9db1362d
license    : MIT
component  : games
summary    : Ajour is a World of Warcraft addon manager written in Rust with a strong focus on performance and simplicity.
description: |
    Ajour is a World of Warcraft addon manager written in Rust with a strong focus on performance and simplicity.
networking : yes
builddeps  :
    - pkgconfig(xft)
    - pkgconfig(xkbcommon)
    - cargo
build      : |
    cargo build --release --no-default-features --features no-self-update,opengl
install    : |
    install -Dm00755 target/release/ajour $installdir/usr/bin/ajour
    install -Dm00644 resources/linux/ajour.desktop $installdir/usr/share/applications/ajour.desktop
    for size in 16 24 32 48 64 128 256 512 1024; do
        install -Dm00644 resources/logo/${size}x${size}/ajour.png $installdir/usr/share/icons/hicolor/${size}x${size}/apps/ajour.png
    done
