name       : ajour
version    : 1.2.1
release    : 3
source     :
    - https://github.com/ajour/ajour/archive/refs/tags/1.2.1.tar.gz : a3a5cbdf654af61336f6c16fef1ca7a8aadcb8f45a1bf11421ba460e78146375
license    : MIT
component  : games
summary    : Ajour is a World of Warcraft addon manager written in Rust with a strong focus on performance and simplicity.
description: |
    Ajour is a World of Warcraft addon manager written in Rust with a strong focus on performance and simplicity.
networking : yes
builddeps  :
    - pkgconfig(xft)
    - cargo
build      : |
    cargo build --release --no-default-features --features opengl
install    : |
    install -Dm00755 target/release/ajour $installdir/usr/bin/ajour
    install -Dm00644 resources/linux/ajour.desktop $installdir/usr/share/applications/ajour.desktop
    for size in 16 24 32 48 64 128 256 512 1024; do
        install -Dm00644 resources/logo/${size}x${size}/ajour.png $installdir/usr/share/icons/hicolor/${size}x${size}/apps/ajour.png
    done
